package com.book.store.entity;

public enum BookGenre {
	
	ADVENTURE,
    FANTASY,
    HISTORICAL_FICTION,
    MYSTERY,
    SCIENCE_FICTION,
    ROMANCE,
    HORROR,
    LITERARY_FICTION,
    YOUNG_ADULT,
    DYSTOPIAN,
    MAGICAL_REALISM,
    GRAPHIC_NOVELS,
    
    BIOGRAPHY,
    SELF_HELP,
    HEALTH_WELLNESS,
    TRUE_CRIME,
    COOKBOOK,
    TRAVEL,
    PHILOSOPHY,
    BUSINESS_ECONOMICS,
    POLITICS,
    PSYCHOLOGY,
    RELIGION_SPIRITUALITY,
    SCIENCE,
    HISTORY,
    
    TEXTBOOKS,
    STUDY_GUIDES,
    LANGUAGE_LEARNING,
    TEST_PREPARATION,
    
    PICTURE_BOOKS,
    EARLY_READERS,
    CHAPTER_BOOKS,
    MIDDLE_GRADE_FICTION,
    
    CLASSICAL_POETRY,
    CONTEMPORARY_POETRY,
    
    ART_HISTORY,
    PHOTOGRAPHY,
    FASHION,
    ARCHITECTURE,
    
    COMICS,
    SHORT_STORIES,
    JOURNALS_PLANNERS,
    
    SPORTS,
    MUSIC,
    PARENTING;

}
